name: Release Socks UI

# This triggers workflow on tag push
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 with Temurin
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Do wrapper
        run: gradle wrapper

      - name: Build JAR file with Gradle
        run: ./gradlew shadowJar

      - name: LS
        run: ls -al SocksUi/build/libs

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SocksUi/build/libs/SocksUi-0.0.8-SNAPSHOT-Intel-all.jar
          asset_name: SocksUi-0.0.8-SNAPSHOT-Intel-all.jar
          asset_content_type: application/gzip
